version: '3.4'

services:
  AutoDataService:
    image: yml-auto-data
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000